silanya/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from markdownx import urls as markdownx

urlpatterns = [
    url(r'^stats/', include ('stats.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include(markdownx)),
]

stats/urls.py
from django.conf.urls import url

from . import views

app_name = 'stats'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^addch/$', views.addch, name='addch'),
    url(r'^character/$', views.CharacterOverviewView.as_view(), name = 'ch_list'),
    url(r'^character/(?P<pk>[a-z,A-Z,0-9]+)/$', views.CharacterView.as_view(), name = 'char_view'),
    url(r'^character/(?P<pk>[a-z,A-Z,0-9]+)/edit$', views.editch, name = 'editch'),
    url(r'^addex/$', views.addex, name='addex'),
    url(r'^expedition/(?P<pk>[a-z,A-Z,0-9]+)/$', views.ExpeditionView.as_view(), name = 'ex_view'),
    url(r'^expedition/(?P<pk>[a-z,A-Z,0-9]+)/edit$', views.editex, name = 'editex'),
    url(r'^expedition/$', views.ExpeditionOverviewView.as_view(), name = 'ex_list'),
]

stats/forms.py
import datetime
from django import forms
from django.forms import formset_factory
from django.utils.safestring import mark_safe
from django.contrib.admin.widgets import AdminDateWidget
from markdownx.fields import MarkdownxFormField
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.admin.widgets import AdminDateWidget

from .models import Player, Expedition, Character, XP

class chStatusWidget(forms.ChoiceField):
    class Media:
        js = ('disable_dd_date.js')

class XPForm(forms.Form):
    char = forms.ModelChoiceField(queryset=Character.objects.all(), label=mark_safe('<br />Name'))#.filter(status!=Character.DEAD).filter(status!=Character.DEPARTED), label='Name')
    value = forms.IntegerField(label='XP')

class AddExForm(forms.Form):
    name = forms.CharField(label='Expedition Name')
    slug = forms.SlugField(label='Expedition Slug')
    dm = forms.ModelChoiceField(queryset=Player.objects.all(),label='DM')
    date = forms.DateField(label='Expedition Date', widget=AdminDateWidget) 

    log = MarkdownxFormField()

    def __init__(self, *args, **kwargs):
        super(AddExForm,self).__init__(*args, **kwargs)
        
class EditExForm(AddExForm):
    slug = forms.SlugField(label='Expedition Slug', disabled=True)

class AddChForm(forms.Form):
    name = forms.CharField(label='Character Name')
    slug = forms.SlugField(label='Slug')
    player = forms.ModelChoiceField(queryset=Player.objects.order_by('name'),label='Player')

class EditChForm(AddChForm):
    STATUS_CHOICES = (
        ('A', 'Alive'),
        ('D', 'Dead'),
        ('G', 'Departed')
    )
#    alive = forms.BooleanField(label='Alive?')
    #status = chStatusWidget(choices=STATUS_CHOICES, initial='Alive', label='Status')
    status = forms.ChoiceField(choices=STATUS_CHOICES, initial='Alive', label='Status', widget=forms.Select(attrs={'onChange':'activateDDField(this)'}))
    dd_date = forms.ModelChoiceField(queryset=Expedition.objects.order_by('-date'),label='Final Expedition', required=False)

class EditAliveChForm(EditChForm):
    dd_date = forms.ModelChoiceField(queryset=Expedition.objects.order_by('-date'),label='Final Expedition', required=False, disabled=True)

class EditDDChForm(EditChForm):
    dd_date = forms.ModelChoiceField(queryset=Expedition.objects.order_by('-date'),label='Final Expedition', required=True, disabled=False)

class CarryXPForm(forms.Form):
    TYPE_CHOICE = (
        ('P', 'Pool'),
        ('L', 'Lump-Sum')
    )
    value = forms.IntegerField(label='XP')
    ex = forms.ModelChoiceField(queryset=Expedition.objects.order_by('-date'), label="After Expedition")
    carrytype = forms.ChoiceField(choices=TYPE_CHOICE, label='Type', initial='Pool')

stats/views.py
import sys
import pdb
import datetime
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.forms import formset_factory
from markdownx.utils import markdownify
from django.utils.safestring import mark_safe

from .models import Character, Expedition, Player, XP, CXP
from .forms import AddExForm, XPForm, EditChForm, AddChForm, CarryXPForm, EditAliveChForm, EditDDChForm

class CharacterView(generic.ListView):
    template_name = 'stats/chardetail.html'
    context_object_name = 'char_detail'
    char = Character()

    def get_queryset(self):#, char):
#        charid = Character.objects.get(slug=pk)
#        char = get_object_or_404(Character, slug=self.request)
        self.char = get_object_or_404(Character, slug=self.kwargs['pk'])
        return Expedition.objects.all().filter(members=self.char)
    
    def get_context_data(self, **kwargs):
        context = super(CharacterView, self).get_context_data(**kwargs)
        context['char'] = Character.objects.get(slug=self.kwargs['pk'])
        return context

class ExpeditionView(generic.ListView):
    template_name = 'stats/exdetail.html'
    context_object_name = 'ex_detail'
    ex = Expedition()

    def get_queryset(self):#, char):
        self.ex = get_object_or_404(Expedition, slug=self.kwargs['pk'])
        return XP.objects.all().filter(expedition=self.ex)
    
    def get_context_data(self, **kwargs):
        context = super(ExpeditionView, self).get_context_data(**kwargs)
        context['ex'] = Expedition.objects.get(slug=self.kwargs['pk'])
        context['log'] = mark_safe(markdownify( Expedition.objects.get(slug=self.kwargs['pk']).log))
        return context

class IndexView(generic.ListView):
    template_name = 'stats/index.html'
    context_object_name = 'character_overview'
        
    def get_queryset(self):
        return Character.objects.order_by('name')
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['allex'] = Expedition.objects.order_by('-date')
        return context

class CharacterOverviewView(generic.TemplateView):
    template_name = 'stats/charlist.html'

    def get_context_data(self, **kwargs):
        context = super(CharacterOverviewView, self).get_context_data(**kwargs)
        context['dead'] = Character.objects.filter(status=Character.DEAD).order_by('name')
        context['gone'] = Character.objects.filter(status=Character.DEPARTED).order_by('name')
        c = Character.objects.exclude(status=Character.DEAD).exclude(status=Character.DEPARTED)
        npc = Player.objects.get(name='NPC')
        context['npc'] = c.filter(player=npc).order_by('name')
        context['pcs'] = c.exclude(player=npc).order_by('name')
        return context

class ExpeditionOverviewView(generic.TemplateView):
    template_name = 'stats/exlist.html'

    def get_context_data(self, **kwargs):
        context = super(ExpeditionOverviewView, self).get_context_data(**kwargs)
        context['exlist'] = Expedition.objects.all().order_by('-date')
        return context

# Create your views here.

def addex(request):
    URL='stats/addex.html'
    CharFormSet = formset_factory(XPForm, extra=1)
    if request.method == 'POST':
        form = AddExForm(request.POST) 
        charformset = CharFormSet(request.POST, prefix='chars')
        charlist = []
    #Validate forms
        if form.is_valid()==False:
            return render(request, URL, {'form':form, 'charformset':charformset})
        if charformset.is_valid()==False:
            return render(request, URL, {'form':form, 'charformset':charformset})
        for c in charformset:
            c.is_valid()
            if c.is_valid()==False or c.cleaned_data == {} or c.cleaned_data['char'] is None or c.cleaned_data['value'] is None:
                return render(request, URL, {'form':form, 'charformset':charformset})
            charlist.append(c.cleaned_data['char'])
        if len(charlist) > len(set(charlist)):
            return render(request, URL, {'form':form, 'charformset':charformset})
        if Expedition.objects.filter(slug=request.POST['slug']).exists():
            # We have a dupe slug, send an error notice
            return render(request, URL, {'form':form, 'charformset':charformset})
        elif 'submit' in request.POST:
            #print(charformset, file=sys.stderr)
            x = Expedition()
            x.dm = Player.objects.get(pk=request.POST['dm'])
            x.name = request.POST['name']
            x.date = request.POST['date']
            x.slug = request.POST['slug']
            x.log = form.cleaned_data['log']
            
            x.save()
            for c in charformset:
                c.is_valid()
                x.members.add(Character.objects.get(pk=c.cleaned_data['char'].pk))
                xp = XP()
                xp.expedition = x
                xp.character = Character.objects.get(pk=c.cleaned_data['char'].pk)
                xp.value = c.cleaned_data['value']
                xp.save()
            x.save()
            return HttpResponseRedirect(reverse('stats:index'))
    else: 
        form = AddExForm()
        charformset = CharFormSet(prefix='chars') 

    return render(request, URL, {'form':form, 'charformset':charformset})

def editex(request, pk):
    URL='stats/editex.html'
    CharFormSet = formset_factory(XPForm, extra=1)
    if request.method == 'POST':
        form = AddExForm(request.POST)
        form.is_valid()
        x = Expedition.objects.get(slug=request.POST['slug'])
        x.dm = Player.objects.get(pk=request.POST['dm'])
        x.name = request.POST['name']
        x.date = form.cleaned_data['date']
        x.log = form.cleaned_data['log']
        x.members.clear()
        charformset = CharFormSet(request.POST, prefix='chars')
        chars_found = []
        for c in charformset:
            c.is_valid()
            char = Character.objects.get(pk=c.cleaned_data['char'].pk)
            x.members.add(char)
            chars_found.append(char)
            if XP.objects.filter(expedition=x).filter(character=char).exists():
                xp = XP.objects.get(expedition=x,character=char)
            else:
                xp = XP()
                xp.expedition = x
                xp.character = char
            xp.value = c.cleaned_data['value']
            xp.save()
        oldchars = XP.objects.filter(expedition=x).exclude(character__in=chars_found)
        for oc in oldchars:
            oc.delete()    
        x.save()
        return HttpResponseRedirect(reverse('stats:index'))
    else: 
        x = Expedition.objects.get(slug=pk);
        form = AddExForm(initial={'dm':x.dm, 'name':x.name, 'date':x.date, 'slug':x.slug, 'log':x.log})
        form['slug'].disabled=True
        CharFormSet= formset_factory(XPForm, extra=0)
        initial_data = []
        for xp in XP.objects.all().filter(expedition=x):
            initial_data.append({'char' : xp.character, 'value' : xp.value,})
        charformset = CharFormSet(prefix='chars', initial=initial_data) 

    return render(request, URL, {'form':form, 'charformset':charformset})

def addch(request):
    URL='stats/addch.html'
    if request.method == 'POST':
        form = AddChForm(request.POST)
        if form.is_valid()==False:
            return render(request, URL, {'form':form})
        if Character.objects.filter(slug=form.cleaned_data['slug']).exists():
            return render(request, URL, {'form':form})
        c = Character()
        c.slug=form.cleaned_data['slug']
        c.name=form.cleaned_data['name']
        c.player=Player.objects.get(pk=form.cleaned_data['player'].pk)
        c.save()
        return HttpResponseRedirect(reverse('stats:index'))
    else:
        form = AddChForm()
    return render(request, URL, {'form':form})

def editch(request,pk):
    URL='stats/editch.html'
    CarryFormset = formset_factory(CarryXPForm, extra=0)
    c = Character.objects.get(slug=pk)
    cx_initial = []
    for cx in CXP.objects.filter(character=c):
        porls = 'L' if cx.lumpNotPool else 'P'
        cx_initial.append({'value':cx.value,'ex':cx.expedition,'carrytype':porls})
    
    if request.method == 'POST':
        form = EditChForm(request.POST)
        carryformset = CarryFormset(request.POST, initial=cx_initial, prefix='carry')
    #Validate form
        if form.is_valid()==False:
            return render(request,URL, {'form':form, 'carryformset':carryformset})
        if carryformset.is_valid()==False:
            return render(request, URL, {'form':form, 'carryformset':carryformset})
        for cx in carryformset:
            cx.is_valid()
            if cx.cleaned_data == {} or cx.cleaned_data['value'] is None \
                        or cx.cleaned_data['ex'] is None or cx.cleaned_data['carrytype'] is None:
                return render(request, URL, {'form':form, 'charformset':charformset})
        c.name = form.cleaned_data['name']
        c.player = Player.objects.get(pk=form.cleaned_data['player'].pk)
        if form.cleaned_data['status']=='A': c.status=Character.ACTIVE
        elif form.cleaned_data['status']=='D': 
            c.status=Character.DEAD
            c.dd_date = Expedition.objects.get(pk=form.cleaned_data['dd_date'].pk).date
        elif form.cleaned_data['status']=='G': c.status=Character.DEPARTED
        c.save()
        for cxp in CXP.objects.filter(character=c):
            cxp.delete()
        for cx in carryformset:
            cxp = CXP()
            cxp.character = c
            cxp.expedition = Expedition.objects.get(pk=cx.cleaned_data['ex'].pk)
            cxp.value = cx.cleaned_data['value']
            cxp.lumpNotPool = cx.cleaned_data['carrytype']!='P'
            cxp.save()
            
        return HttpResponseRedirect(reverse('stats:index'))
    else:

stats/templates/stats/add.html
{% load staticfiles %}
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src={% static 'stats/add/js/jquery.formset.js' %}></script>

<h1> Add New Expedition </h1>
{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
{% if charformset.errors %}<p><strong>{{ charformset.errors }}</strong></p>{% endif %}
{% if charformset.errors %}<p><strong>{{ charformset.non_form_errors }}</strong></p>{% endif %}
{% for row in charformset %}
{% if row.errors %}<p><strong>{{ row.errors }}</strong></p>{% endif %}
{% endfor %}

<form method="post" id="addExForm">
	{% csrf_token %}
	{{ form |linebreaks}}
	<table> <tbody>
	{% for row in charformset.forms %}
	<tr id="{{ row.prefix }}-row">
		<td> {{ row.char }} </td>
		<td> {{ row.value }} </td>
	</tr>
	{% endfor %}
	</tbody> </table>
	{{ charformset.management_form }}
	<script type="text/javascript">
		$(function() {
			$('#addExForm tbody tr').formset({
				prefix: "{{ charformset.prefix }}"
				});
		}) 
	</script>	
	<br />
<input type="submit" name="submit" value="done" />
</form>

stats/templates/stats/addch.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
{% endblock %}
{% block page %}
<h1> Add New Character </h1>
{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
<form method="post" id="addChForm">
	{% csrf_token %}
	{{ form |linebreaks}}
	<br />
<input type="submit" name="submit" value="done" />
</form>
{% endblock %}

stats/templates/stats/addex.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
<link rel="stylesheet" type="text/css" href={% static 'stats/css/ex.css' %} >
<link rel="stylesheet" type="text/css" href={% static 'admin/css/base.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'admin/css/widgets.css' %}>
<script type=text/javascript src={% static 'stats/js/jsi18n' %}></script>
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type="text/javascript" src={% static 'admin/js/core.js' %}></script>
<script type="text/javascript" src={% static 'admin/js/jquery.init.js' %}></script>
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src={% static 'stats/js/jquery.formset.js' %}></script>

{% endblock %}
{% block page %}

<h1> Add New Expedition </h1>
{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
{% if charformset.errors %}<p><strong>{{ charformset.errors }}</strong></p>{% endif %}
{% if charformset.errors %}<p><strong>{{ charformset.non_form_errors }}</strong></p>{% endif %}
{% for row in charformset %}
{% if row.errors %}<p><strong>{{ row.errors }}</strong></p>{% endif %}
{% endfor %}

<form method="post" id="addExForm">
	{% csrf_token %}
	{{ form |linebreaks}}
	<table> <tbody>
	{% for row in charformset.forms %}
	<tr id="{{ row.prefix }}-row">
		<td> {{ row.char }} </td>
		<td> {{ row.value }} </td>
	</tr>
	{% endfor %}
	</tbody> </table>
	{{ charformset.management_form }}
	<script type="text/javascript">
		$(function() {
			$('#addExForm tbody tr').formset({
				prefix: "{{ charformset.prefix }}"
				});
		}) 
	</script>	
	<br />
<input type="submit" name="submit" value="done" />
</form>
{{ form.media }}
{% endblock %}

stats/templates/stats/chardetail.html
{% extends "base.html" %}
{% block page %}
<h1> {{char.name}} </h1>
<a href="{% url 'stats:editch' char.slug %}">Edit</a>
{% if char_detail %}
    <ul>
    {% for ex in char_detail %}
        <li>{{ex.name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No expeditions yet.</p>
{% endif %}
{% endblock %}

stats/templates/stats/charlist.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
<link rel="stylesheet" type="text/css" href={% static 'stats/css/charlist.css' %}>
{% endblock %}
{% block page %}
<h3> Alive </h3>
<ul class=characters>
{% for c in pcs %}
	<li> <a href={% url 'stats:char_view' c.slug %}>{{ c.name }}</a></li>
{% endfor %}
</ul>
<h3> Shared Characters</h3>
<ul class=characters>
{% for c in npc %}
	<li> <a href={% url 'stats:char_view' c.slug %}>{{ c.name }}</a></li>
{% endfor %}
</ul>
<h3> Dead PCs </h3>
<ul class=characters>
{% for c in dead %}
	<li> <a href={% url 'stats:char_view' c.slug %}>{{ c.name }}</a></li>
{% endfor %}
</ul>
<h3> Departed PCs </h3>
<ul class=characters>
{% for c in gone %}
	<li> <a href={% url 'stats:char_view' c.slug %}>{{ c.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

stats/templates/stats/edit.html
{% load staticfiles %}
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src={% static 'stats/add/js/jquery.formset.js' %}></script>

<h1> Editing Expedition </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post" id="addExForm">
	{% csrf_token %}
<!--	{{ form |linebreaks}} -->
	{% for field in form %}
		{% if field.label == "Expedition Slug" %}
			{{ field.as_hidden }}
		{% else %}
			{{ field.label }}:{{ field }} <br>
		{% endif %}
	{% endfor %}
	<table> <tbody>
	{% for row in charformset.forms %}
	<tr id="{{ row.prefix }}-row">
		<td> {{ row.char }} </td>
		<td> {{ row.value }} </td>
	</tr>
	{% endfor %}
	</tbody> </table>
	{{ charformset.management_form }}
	<script type="text/javascript">
		$(function() {
			$('#addExForm tbody tr').formset({
				prefix: "{{ charformset.prefix }}"
				});
		}) 
	</script>	
	<br />
<input type="submit" name="submit" value="done" />
</form>

stats/templates/stats/editch.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extraheaders %}
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src={% static 'stats/js/jquery.formset.js' %}></script>
{% endblock %}
{% block page %}

<h1> Editing Character </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<table>
	<tbody>
	{% with carryformset.empty_form as ef %}
	<tr id="empty_carry_form" style="display:none;" >
	{% for fields in ef %}
	<td>{{ fields }}</td>
	{% endfor %}
	</tr>
	{% endwith %}
	</tbody>
</table>
<form method="post" id="editChForm">
	{% csrf_token %}
	{% for field in form %}
		{% if field.label == "Slug" %}
			{{ field.as_hidden }}
		{% else %}
			{{ field.label }}:{{ field }} <br>
		{% endif %}
	{% endfor %}
	<table class="cxp"> <tbody> 
{% if carryformset.initial_form_count == 0 %}
	<tr style="display:none;"></tr>
{% else %}
	{% for row in carryformset.forms %}
	<tr id="{{ row.prefix }}-row">
		<td> {{ row.value }} </td>
		<td> {{ row.ex }} </td>
		<td> {{ row.carrytype }} </td>
	</tr>
	{% endfor %}
{% endif %}
	</tbody>
	</table>
	{{ carryformset.management_form }}
	<br />
<input type="submit" name="submit" value="done" />
</form>
	<script type="text/javascript">
		$(function() {
			$('#editChForm table.cxp tbody tr').formset({
				prefix: 'carry',
{% if carryformset.initial_form_count == 0 %}
				formTemplate: '#empty_carry_form',
{% endif %}
				});
		}) 
	</script>	

	<script type="text/javascript">
	function activateDDField(obj) {
		var ddf = document.getElementById("id_dd_date");
		ddf.required =  obj.value != "A";
		ddf.disabled = obj.value == "A";
	}
	</script>
{% endblock %}

stats/templates/stats/editex.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n admin_modify %}
{% block extraheaders %}
<link rel="stylesheet" type="text/css" href={% static 'stats/css/ex.css' %} >
<link rel="stylesheet" type="text/css" href={% static 'admin/css/base.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'admin/css/widgets.css' %}>
<script type="text/javascript" src={% static 'stats/js/jsi18n' %}></script>
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type="text/javascript" src={% static 'admin/js/core.js' %}></script>
<script type="text/javascript" src={% static 'admin/js/jquery.init.js' %}></script>
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src={% static 'stats/js/jquery.formset.js' %}></script>
{% endblock %}
{% block page %}

<h1> Editing Expedition </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post" id="addExForm">
	{% csrf_token %}
	{% for field in form %}
		{% if field.label == "Expedition Slug" %}
			{{ field.as_hidden }}
		{% else %}
			{{ field.label }}:{{ field }} <br>
		{% endif %}
	{% endfor %}
	<table> <tbody>
	{% for row in charformset.forms %}
	<tr id="{{ row.prefix }}-row">
		<td> {{ row.char }} </td>
		<td> {{ row.value }} </td>
	</tr>
	{% endfor %}
	</tbody> </table>
	{{ charformset.management_form }}
	<script type="text/javascript">
		$(function() {
			$('#addExForm tbody tr').formset({
				prefix: "{{ charformset.prefix }}"
				});
		}) 
	</script>	
	<br />
<input type="submit" name="submit" value="done" />
</form>

{{ form.media }}
{% endblock %}

stats/templates/stats/exdetail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
{% endblock %}
{% block page %}
<h1> {{ex.name}} </h1>
<a href="{% url 'stats:editex' ex.slug %}">Edit</a>
{% if ex_detail %}
    <ul>
    {% for x in ex_detail %}
        <li>{{ x.character }}: {{ x.value }}</li>
    {% endfor %}
    </ul>
	{{ log }}
{% else %}
    <p>No expeditions yet.</p>
{% endif %}
{% endblock %}

stats/templates/stats/exlist.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
<link rel="stylesheet" type="text/css" href={% static 'stats/css/charlist.css' %}>
{% endblock %}
{% block page %}
{% for ex in exlist %}
<a href={% url 'stats:ex_view' ex.slug%}>{{ex.name}}</a> - Some description <br>
{% endfor %}
{% endblock %}

stats/templates/stats/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extraheaders %}
<link rel="stylesheet" type="text/css" href={% static 'stats/css/table.css' %} >
<script type=text/javascript src={% static 'static_jquery/js/jquery.js' %}></script>
<script type=text/javascript src="https://mottie.github.io/tablesorter/js/jquery.tablesorter.js"></script>
<!-- <script type=text/javascript src={% static 'stats/js/jquery.tablesorter.js' %}></script> -->
<!-- <script type=text/javascript src={% static 'stats/js/jquery.CongelarFilaColumna.js' %}></script> -->
{% endblock %}
{% block page %}

{% if character_overview %}
<div class="tablediv">
<table id="allChars" class="tablesorter">
	<thead> <tr> <th class="headcol"><a href="{% url 'stats:addex' %}">New Ex</a> <br> <a href="{% url 'stats:addch' %}">New Char</a></th> 
	<th>Status</th><th>Level</th><th>Total XP</th><th> Next Level</th> 
	{% for ex in allex %}
		<th> <a href="{% url 'stats:ex_view' ex.slug %}">{{ex.name}} </a></th>
	{% endfor %}
	</tr>
	</thead>
	<tbody>
	{% for char in character_overview %}
		<tr class="char_{{char.status}}">
		<th class="headcol char_{{char.status}}"> <a class="char_{{char.status}}" href="{% url 'stats:char_view' char.slug %}">{{ char.tableName }}</a> </td>
		{% for xp in char.tableInfo %}
			<td> {{ xp }} </td>
		{% endfor %}
		</tr>
	{% endfor %}
	</tbody>
</table>
</div>
<script type="text/javascript">
$(document).ready(function()
	{
		$("#allChars").tablesorter(
			{cancelSelection: false,
			tableClass: "tablesorter",
			cssAsc: "headerSortUp",
			cssDesc: "headerSortDown",
			cssHeader: "header",}
		);
	}
);
</script>
{% else %}
    <p>No characters are available.</p>
{% endif %}
{% endblock %}